services:
  tests:
    networks:
      - default
      - jenkins-infrastructure

networks:
  jenkins-infrastructure:
    name: "${CI_INFRASTRUCTURE_NETWORK:-infraestrutura-network}"
    external: true
