const Bcrypt = require("bcryptjs");
const jwt = require('jsonwebtoken');

const User = require('../models/User');

const sendUser = require('../utils/sendEmail');

module.exports = {

    async userProfile(req, res) {
        try {
            const user = await User.findById(req.userId);
            console.log("User.show | user: ",user);

            if(!user) {
                return res.status(400).send({ message: "The user does not exist" });
            }
            console.log("User.show | req.userId: ",req.userId);

            var userWithoutPassword = user.toObject();
            delete userWithoutPassword.password;

            return res.json(userWithoutPassword);
        } catch (error) {
            console.log("User.show | error: ",error);
            res.status(500).send(error);
        }
    },

    async userSignUp(req, res) {
        try {
            req.body.password = Bcrypt.hashSync(req.body.password, 10);
            const user = await User.create(req.body);

            let message = {
                from: `${process.env.ACCOUNT_NAME} <${process.env.ACCOUNT_EMAIL}>`,
                to: req.body.email,
                subject: 'Welcome',
                text: 'Successful registration!',
                html: '<p>Successful registration!</p>'
            };
            
            console.log("User.store | message: ",message);

            const responseEmail = sendUser(message);

            console.log("User.store | responseEmail: ",responseEmail);
    
            return res.json(user);
        } catch (error) {
            console.log("User.store | error: ",error);
            res.status(500).send(error);
        }
    },

    async userUpdate(req, res) {
        try {
            const user = await User.findByIdAndUpdate(req.userId, req.body, {   
                new: true
            });

            return res.json(user);
        } catch (error) {
            console.log("User.update | error: ",error);
            res.status(500).send(error);
        }
    },

    async userDelete(req, res) {
        try {
            const user = await User.findByIdAndRemove(req.userId);

            if(!user) {
                return res.status(400).send({ message: "The user does not exist" });
            }

            res.send({ message: "successfully deleted" });
        } catch (error) {
            console.log("User.destroy | error: ",error);
            res.status(500).send({ message: error.message });
        }
    },

    async userSignIn(req, res) {
        try {
            const user = await User.findOne({ email: req.body.email });
            if(!user) {
                return res.status(400).send({ message: "The email does not exist" });
            }
            if(!Bcrypt.compareSync(req.body.password, user.password)) {
                return res.status(403).send({ message: "The password is invalid" });
            }

            const token = jwt.sign({ id: user["_id"] }, process.env.JWT_SECRET, { expiresIn: "14 days" });

            res.send({ 
                auth: true,
                token, 
                message: "E-mail and password are correct!" 
            });
            
        } catch (error) {
            console.log("User.login | error: ",error);
            res.status(500).send(error);
        }
    },

    async userForgotPassword(req, res) {
        try {
            const user = await User.findOne({ email: req.body.email });
            if(!user) {
                return res.status(400).send({ message: "The email does not exist" });
            }

            const randomText = Math.random().toString(36).slice(2); 
            console.log("User.forgotPassword | new password: ",randomText);

            let encryptedPassword = Bcrypt.hashSync(randomText, 10);

            await User.findByIdAndUpdate(
                user["_id"], 
                { password: encryptedPassword }
            );

            let message = {
                from: `${process.env.ACCOUNT_NAME} <${process.env.ACCOUNT_EMAIL}>`,
                to: user.email,
                subject: 'New password generated by the "I forgot my password" feature',
                text: `Your New Password: ${randomText}`,
                html: `<p><strong>Your New Password:</strong> ${randomText}</p>`
            };
            
            console.log("User.store | message: ",message);

            const responseEmail = sendUser(message);

            console.log("User.store | responseEmail: ",responseEmail);

            res.send({ message: "Your new password was successfully generated and sent to the email registered in the profile." });
        } catch (error) {
            console.log("User.forgotPassword | error: ",error);
            res.status(500).send(error);
        }
    },

    async userRedefinePassword(req, res) {
        try {
            console.log("redefinePassword | req.userId: ",req.userId);
            
            if(req.body.newPassword !== req.body.confirmNewPassword) {
                return res.status(400).send({ message: "Password and confirm password fields are different" });
            }
            
            const user = await User.findById(req.userId);

            if(!user) {
                return res.status(400).send({ message: "The user does not exist" });
            }

            if(!Bcrypt.compareSync(req.body.currentPassword, user.password)) {
                return res.status(400).send({ message: "The password is invalid" });
            }

            let encryptedPassword = Bcrypt.hashSync(req.body.newPassword, 10);

            await User.findByIdAndUpdate(
                user["_id"],
                { password: encryptedPassword }
            );

            let message = {
                from: `${process.env.ACCOUNT_NAME} <${process.env.ACCOUNT_EMAIL}>`,
                to: user.email,
                subject: 'Your password has been reset',
                text: 'If you have not changed your password, contact us immediately.',
                html: '<p>If you have not changed your password, contact us immediately.</p>'
            };
            
            console.log("User.store | message: ",message);

            const responseEmail = sendUser(message);

            console.log("User.store | responseEmail: ",responseEmail);

            res.send({ message: "Password successfully reset!" });
        } catch (error) {
            console.log("User.redefinePassword | error: ",error);
            res.status(500).send(error);
        }

    }
}